name: VPS Session
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tmate
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq tmate
      - name: Start tmate
        run: |
          tmate -F -n vps new-session -d
          sleep 3
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          tmate -S /tmp/tmate.sock wait tmate-ready
          sleep 21600
