name: VPS Session
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
